<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SpecEdu.Application\SpecEdu.Application.csproj" />
    <ProjectReference Include="..\SpecEdu.Infrastructure\SpecEdu.Infrastructure.csproj" />
  </ItemGroup>

</Project>
