{{- if .Values.webPublic.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-public
  labels:
    app: specedu
    component: web-public
spec:
  replicas: {{ .Values.webPublic.replicas }}
  selector:
    matchLabels:
      app: specedu
      component: web-public
  template:
    metadata:
      labels:
        app: specedu
        component: web-public
    spec:
      containers:
        - name: web-public
          image: "{{ .Values.webPublic.image.repository }}:{{ .Values.webPublic.image.tag }}"
          imagePullPolicy: {{ .Values.webPublic.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.webPublic.service.port }}
              name: http
          envFrom:
            - secretRef:
                name: specedu-app
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: {{ .Values.environment | quote }}
            - name: ASPNETCORE_FORWARDEDHEADERS_ENABLED
              value: "true"
            - name: AppUrl
              value: "https://{{ index .Values.webApp.ingress.hosts 0 }}"
          resources:
            {{- toYaml .Values.webPublic.resources | nindent 12 }}
          livenessProbe:
            tcpSocket:
              port: {{ .Values.webPublic.service.port }}
            initialDelaySeconds: {{ .Values.healthChecks.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.healthChecks.liveness.periodSeconds }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.webPublic.service.port }}
            initialDelaySeconds: {{ .Values.healthChecks.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.healthChecks.readiness.periodSeconds }}
{{- end }}
{{- if .Values.webApp.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  labels:
    app: specedu
    component: web-app
spec:
  replicas: {{ .Values.webApp.replicas }}
  selector:
    matchLabels:
      app: specedu
      component: web-app
  template:
    metadata:
      labels:
        app: specedu
        component: web-app
    spec:
      containers:
        - name: web-app
          image: "{{ .Values.webApp.image.repository }}:{{ .Values.webApp.image.tag }}"
          imagePullPolicy: {{ .Values.webApp.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.webApp.service.port }}
              name: http
          envFrom:
            - secretRef:
                name: specedu-app
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: {{ .Values.environment | quote }}
            - name: ASPNETCORE_FORWARDEDHEADERS_ENABLED
              value: "true"
            - name: PublicUrl
              value: "https://{{ index .Values.webPublic.ingress.hosts 0 }}"
          resources:
            {{- toYaml .Values.webApp.resources | nindent 12 }}
          livenessProbe:
            tcpSocket:
              port: {{ .Values.webApp.service.port }}
            initialDelaySeconds: {{ .Values.healthChecks.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.healthChecks.liveness.periodSeconds }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.webApp.service.port }}
            initialDelaySeconds: {{ .Values.healthChecks.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.healthChecks.readiness.periodSeconds }}
{{- end }}
