{{- if .Values.webPublic.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: web-public
  labels:
    app: specedu
    component: web-public
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.webPublic.service.port }}
      targetPort: {{ .Values.webPublic.service.port }}
      protocol: TCP
      name: http
  selector:
    app: specedu
    component: web-public
{{- end }}
{{- if .Values.webApp.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: web-app
  labels:
    app: specedu
    component: web-app
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.webApp.service.port }}
      targetPort: {{ .Values.webApp.service.port }}
      protocol: TCP
      name: http
  selector:
    app: specedu
    component: web-app
{{- end }}
